from typing import Any, Protocol

from app.contracts.wordpress_v1 import WordPressPayloadV1


class PublicationPort(Protocol):
    def find(self, slug: str) -> dict[str, Any] | None: ...

    def get(self, post_id: str) -> dict[str, Any]: ...

    def create_draft(self, payload: WordPressPayloadV1) -> dict[str, Any]: ...

    def publish(self, post_id: str) -> dict[str, Any]: ...
